### PR TITLE
Scale Measure Unit function

### PR DESCRIPTION
**Pull request by AndreaGreco**
Add Scale measure unit function, it group all other function.

### CODE REVIEW

**Comment by hryamzik** [comment]
Hi @AndreaGreco, looks like incaller's  CI has some issues so I ran tests manually and some of them failed:

```
$ prove -v
t/curl.t .. 
1..16
ok 1 - emptyValue.json template none
ok 2 - noGenURL.json template none
ok 3 - production_example.json template none
ok 4 - simpe.json template none
ok 5 - emptyValue.json template default.tmpl
ok 6 - noGenURL.json template default.tmpl
ok 7 - production_example.json template default.tmpl
ok 8 - simpe.json template default.tmpl
ok 9 - emptyValue.json template detailed_vars.tmpl
ok 10 - noGenURL.json template detailed_vars.tmpl
ok 11 - production_example.json template detailed_vars.tmpl
ok 12 - simpe.json template detailed_vars.tmpl
not ok 13 - emptyValue.json template production_example.tmpl
not ok 14 - noGenURL.json template production_example.tmpl
not ok 15 - production_example.json template production_example.tmpl
not ok 16 - simpe.json template production_example.tmpl
Failed 4/16 subtests 
```

I don't have time to dig through this but tests have to be green for a merge.

**Comment by AndreaGreco** [comment]
Config file, miss parameter.

Charter for split field

Il 26 apr 2017 16:48, "Roman Belyakovsky" <notifications@github.com> ha
scritto:

**Comment by AndreaGreco** [comment]
Required for test:
``` yaml
telegram_token: ""
template_path: ""
time_zone: "Europe/Rome"
time_outdata: "02/01/2006 15:04:05"
split_token: "|" <-------- THIS
```

**Comment by hryamzik** [comment]
So you want to test this with different configs, that looks complicated. Can you make a default value for this setting? I'm going to keep test config unchanged to ensure new code is compatible with original configuration.

**Comment by AndreaGreco** [comment]
Done

**Comment by hryamzik** [comment]
Thanks!

**Pull request merged**
