### PR TITLE
Bump alpine 3.14

### PR DESCRIPTION
**Pull request by aminvakil**

### CODE REVIEW

**Comment by aminvakil** [comment]
FYI It's been a while I've switched to alpine 3.14 and it builds just fine:
https://github.com/aminvakil/prometheus_bot/actions

**Comment by aminvakil** [comment]
Builder is currently using `golang:1.14.4-alpine3.12` as base image and `golang:1.14.4-alpine3.14` is not available.

What do you think about upgrading this to use golang 1.16 or 1.17 as 1.14 has been EOLed about 1 year and 8 months ago?

Do you want me to open a new PR regarding that or add commits to this branch?

**Comment by hryamzik** [comment]
Let's add all versions up here.

**Comment by aminvakil** [comment]
> Let's add all versions up here.

Done.

**Review by hryamzik — APPROVED** [review]

**Comment by hryamzik** [comment]
LGTM, ty!

**Pull request merged**
