### PR TITLE
aminvakil merge

### PR DESCRIPTION
**Pull request by aminvakil**
As discussed in https://github.com/inCaller/prometheus_bot/pull/117#issuecomment-2538756167

I'm merging all my commits from there to here.

This also adds ghcr.io deployment.

### CODE REVIEW

**Comment by aminvakil** [comment]
@hryamzik I cannot approve and merge my own request, and I cannot push to master.

Would you please merge this and later #119 ?

**Comment by hryamzik** [comment]
That's on purpose, at least one other person should review PRs

**Review by hryamzik — APPROVED** [review]

**Comment by aminvakil** [comment]
> That's on purpose, at least one other person should review PRs

Fine, should I mention you every time I open a PR? I'm fine with that, just let me know.

**Comment by hryamzik** [comment]
you can add me as a reviewer

**Pull request merged**
