### PR TITLE
Add alert duration field [feature]

### PR DESCRIPTION
**Pull request by mywkaa**
Hello,

Added new field "Duration" with time.Duration format , it equals of subtraction between endsAt and startsAt fields.

Example alert resolved: 
`{  
   "alerts":[  
      {  
         "annotations":{  
            "resolve_message":"node-exporter is available test12345",
            "summary":"node-exporter is not available during 5 minute test12345"
         },
         "endsAt":"2018-06-05T09:18:45.237509292Z",
         "generatorURL":"1111",
         "labels":{ 
            "alertname":"Node exporter availability during 5 minute 12345",
            "instance":"22222",
            "severity":"critical"
         },
         "startsAt":"2018-06-05T09:17:45.237509292Z",
         "Duration":60000000000
      }
   ]
}`

### CODE REVIEW

**Comment by mywkaa** [comment]
In go templating this field looks like :
`  {{ range $val := .Alerts -}}
  Alert duration: {{$val.Duration}}
  {{ end }}`

result:
`Alert duration : 1m0s`

**Comment by hryamzik** [comment]
So is result human-readable? Simple duration output is usually in milliseconds.

Can you also update README, please?

**Comment by mywkaa** [comment]
> So is result human-readable? Simple duration output is usually in milliseconds.
Yes result is human readable, added "Truncate" to seconds to avoid ms output.

> Can you also update README, please?
README has no fields related documentation. Should I add new testdata file ?

**Comment by hryamzik** [comment]
@mywkaa Please add usage to readme and I'll be able to merge this

**Review by hryamzik — CHANGES_REQUESTED** [review]
@mywkaa Please add usage to readme and I'll be able to merge this

**Comment by hryamzik** [comment]
No updates so I have to close this

**Pull request closed without merging**
